export const COMPONENTS_PATH = "/components";

export const COMPONENTS_STRING_PATH = COMPONENTS_PATH + "/string";
export const COMPONENTS_STRING_TEXT_PATH = COMPONENTS_STRING_PATH + "/text";
export const COMPONENTS_STRING_SELECT_PATH = COMPONENTS_STRING_PATH + "/select";

export const COMPONENTS_BOOLEAN_PATH = COMPONENTS_PATH + "/boolean";
export const COMPONENTS_BOOLEAN_CHECKBOX_PATH = COMPONENTS_BOOLEAN_PATH + "/checkbox";
export const COMPONENTS_BOOLEAN_SELECT_PATH = COMPONENTS_BOOLEAN_PATH + "/select";

export const COMPONENTS_OBJECT_PATH = COMPONENTS_PATH + "/object";
export const COMPONENTS_OBJECT_GRID_PATH = COMPONENTS_OBJECT_PATH + "/grid";

export const DOCUMENTATION_PATH = "/documentation";

export const DOCUMENTATION_SCHEMA_PATH = DOCUMENTATION_PATH + "/schema";

export const DOCUMENTATION_CONFIG_SCHEMA_PATH = DOCUMENTATION_PATH + "/configSchema";
export const DOCUMENTATION_CONFIG_SCHEMA_ELEMENTS_PATH = DOCUMENTATION_CONFIG_SCHEMA_PATH + "/elements";
export const DOCUMENTATION_CONFIG_SCHEMA_LAYOUT_PATH = DOCUMENTATION_CONFIG_SCHEMA_PATH + "/layout";
export const DOCUMENTATION_CONFIG_SCHEMA_STYLES_PATH = DOCUMENTATION_CONFIG_SCHEMA_PATH + "/styles";

export const DOCUMENTATION_TYPES_PATH = DOCUMENTATION_PATH + "/types";

export const DOCUMENTATION_TYPES_STRING_PATH = DOCUMENTATION_TYPES_PATH + "/string";
export const DOCUMENTATION_TYPES_BOOLEAN_PATH = DOCUMENTATION_TYPES_PATH + "/boolean";
export const DOCUMENTATION_TYPES_OBJECT_PATH = DOCUMENTATION_TYPES_PATH + "/object";

export const DOCUMENTATION_EVENTS_PATH = DOCUMENTATION_PATH + "/events";

export const DOCUMENTATION_DEFAULTS_PATH = DOCUMENTATION_PATH + "/defaults";

export const EXAMPLES_PATH = "/examples";


export const SOLUTIONS_PATH = "/solutions";